name: "${STACK_NAME:-portfolio}"

networks:
  webnet:
    driver: bridge

services:
  nginx:
    image: ghcr.io/jargonless-website/portfolio-web:${WEB_IMAGE_TAG:-latest}
    depends_on: [api]
    expose: ["80"]              # internal only
    networks: [webnet]

  api:
    image: ghcr.io/jargonless-website/portfolio-api:${API_IMAGE_TAG:-latest}
    environment:
      - ENV=${ENV:-development}
    expose: ["8000"]            # internal only
    networks: [webnet]

  jl_tunnel:
    image: cloudflare/cloudflared:latest
    restart: always
    # Read token from env files (prod will supply them)
    env_file:
      - ${APP_ENV_FILE:-./.env.production}
      - ${TUNNEL_ENV_FILE:-./.env.tunnel}
    command:
      - tunnel
      - --config
      - /etc/cloudflared/config.yml
      - run
      - --token
      - ${CLOUDFLARE_TUNNEL_TOKEN}
    volumes:
      - ${TUNNEL_VOLUME:-/volume1/docker/portfolio/cloudflared}:/etc/cloudflared
    networks: [webnet]
