x-common-logging: &common_logging
  driver: json-file
  options: { max-size: "10m", max-file: "5" }

x-common-resources: &common_resources
  deploy:
    resources:
      limits: { memory: "512M" }
      reservations: { memory: "128M" }

services:
  nginx:
    container_name: portfolio-nginx-1            # <— add this
    restart: unless-stopped
    ports: []                                     # no host port in prod
    environment: [NODE_ENV=production]
    volumes:
      - ./../nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./../nginx/snippets:/etc/nginx/snippets:ro
    read_only: true
    tmpfs: [/var/cache/nginx, /var/run, /var/log/nginx]
    security_opt: [no-new-privileges:true]
    cap_drop: [NET_ADMIN, SYS_ADMIN]
    healthcheck:
      test: ["CMD-SHELL","wget -qO- http://localhost/ || exit 1"]
      interval: 15s
      timeout: 3s
      retries: 10
      start_period: 20s
    logging: *common_logging
    <<: *common_resources

  api:
    container_name: portfolio-api-1              # <— add this
    restart: unless-stopped
    env_file:
      - ./.env.production                         # <— keep it relative to THIS file
    environment:
      - ENV=production
      - CORS_ORIGINS=https://jargonless.ai
    ports: []                                     # no host port in prod
    read_only: true
    tmpfs: [/tmp]
    security_opt: [no-new-privileges:true]
    cap_drop: [SYS_ADMIN, NET_ADMIN]
    healthcheck:
      test:
        - CMD-SHELL
        - >
          python -c "import sys,urllib.request,socket;
          socket.setdefaulttimeout(3);
          sys.exit(0 if urllib.request.urlopen('http://localhost:8000/api/health').getcode()==200 else 1)"
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s
    logging: *common_logging
    <<: *common_resources

  jl_tunnel:                                      # <— add this whole service
    container_name: portfolio-jl_tunnel-1
    image: cloudflare/cloudflared:latest
    restart: always
    command: ["tunnel","--config","/etc/cloudflared/config.yml","run","--token","${CLOUDFLARE_TUNNEL_TOKEN}"]
    env_file:
      - ./.env.tunnel                             # lives next to this compose file
    volumes:
      - /volume1/docker/portfolio/cloudflared:/etc/cloudflared
