services:
  api:
    build:
      context: ../../apps/api
    image: jargonless/api:week0
    container_name: jl_api_week0
    ports:
      - "8000:8000"
    networks: [webnet]

  nginx:
    image: nginx:alpine
    container_name: jl_nginx_week0
    depends_on: [api]
    ports:
      - "8080:80"
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../nginx/html:/usr/share/nginx/html:ro
    networks: [webnet]

networks:
  webnet: {}
