name: "${STACK_NAME:-portfolio}"

networks:
  webnet:
    driver: bridge

services:
  nginx:
    image: ghcr.io/jargonless-website/portfolio-web:${WEB_IMAGE_TAG:-latest}
    depends_on: [api]
    expose: ["80"]                 # internal only
    networks: [webnet]

  api:
    image: ghcr.io/jargonless-website/portfolio-api:${API_IMAGE_TAG:-latest}
    environment:
      - ENV=${ENV:-development}    # picked up from --env-file at deploy time
      - CORS_ORIGINS=${CORS_ORIGINS:-http://localhost:5173}
    expose: ["8000"]               # internal only
    networks: [webnet]

  jl_tunnel:
    image: cloudflare/cloudflared:latest
    restart: always
    command: ["sh","-lc","tunnel run --token \"$CLOUDFLARE_TUNNEL_TOKEN\""]
    volumes:
      - ${TUNNEL_VOLUME:-/volume1/docker/portfolio/cloudflared}:/etc/cloudflared
    networks: [webnet]
