name: portfolio

networks:
  webnet:
    driver: bridge

services:
  nginx:
    image: ghcr.io/jargonless-website/portfolio-web:latest
    depends_on:
      - api
    ports:
      - "8080:80"
    networks: [webnet]

  api:
    image: ghcr.io/jargonless-website/portfolio-api:latest
    environment:
      - ENV=${ENV:-development}
    ports:
      - "8000:8000"
    networks: [webnet]

  jl_tunnel:
    image: cloudflare/cloudflared:latest
    restart: always
    command: ["tunnel","--config","/etc/cloudflared/config.yml","run","--token","${CLOUDFLARE_TUNNEL_TOKEN}"]
    volumes:
      - /volume1/docker/portfolio/cloudflared:/etc/cloudflared
    networks: [webnet]
