# Cloudflared staging (kept for reference; token mode uses CF dashboard config)
ingress:
  - hostname: staging.jargonless.ai
    service: http://nginx:80
  - hostname: api.staging.jargonless.ai
    service: http://api:8000
  - service: http_status:404

# Top-level (same indent as 'ingress:')
protocol: http2
edge-ip-version: "4"
no-autoupdate: true
ha-connections: 4
