# Cloudflared staging (kept for reference; token mode uses CF dashboard config)
ingress:
  - hostname: staging.jargonless.ai
    service: http://nginx:80
  - service: http_status:404

protocol: http2
edge-ip-version: "4"
no-autoupdate: true
ha-connections: 4
