tunnel: bffd373b-604d-4fb3-b8ae-03cf6d797f6e

ingress:
  - hostname: staging.jargonless.ai
    service: http://nginx:80
  - hostname: api.staging.jargonless.ai
    service: http://api:8000
  - service: http_status:404

protocol: http2
edge-ip-version: "4"
no-autoupdate: true
ha-connections: 4
