name: Build & Push Images

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    if: github.event_name != 'pull_request'
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_TOKEN }}

      # optional: avoid Docker Hub flakiness
      - name: Pre-pull base images (retry)
        run: |
          set -e
          for i in 1 2 3; do docker pull node:20-alpine && break || sleep 5; done
          for i in 1 2 3; do docker pull nginx:1.27-alpine && break || sleep 5; done
          for i in 1 2 3; do docker pull python:3.11-slim && break || sleep 5; done

      - name: Build & push WEB
        run: |
          docker build -f ./apps/web/Dockerfile -t ghcr.io/jargonless-website/portfolio-web:${{ github.sha }} ./apps/web
          docker tag ghcr.io/jargonless-website/portfolio-web:${{ github.sha }} ghcr.io/jargonless-website/portfolio-web:latest
          docker push ghcr.io/jargonless-website/portfolio-web:${{ github.sha }}
          docker push ghcr.io/jargonless-website/portfolio-web:latest

      - name: Build & push API
        run: |
          docker build -f ./apps/api/Dockerfile -t ghcr.io/jargonless-website/portfolio-api:${{ github.sha }} ./apps/api
          docker tag ghcr.io/jargonless-website/portfolio-api:${{ github.sha }} ghcr.io/jargonless-website/portfolio-api:latest
          docker push ghcr.io/jargonless-website/portfolio-api:${{ github.sha }}
          docker push ghcr.io/jargonless-website/portfolio-api:latest
