name: Build & push images to GHCR

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  packages: write

jobs:
  build:
    if: github.event_name != 'pull_request'
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u "${{ secrets.GHCR_USER }}" --password-stdin

      - name: Build & push WEB (latest + SHA)
        run: |
          docker build -t ghcr.io/jargonless-website/portfolio-web:${{ github.sha }} ./apps/web
          docker tag ghcr.io/jargonless-website/portfolio-web:${{ github.sha }} ghcr.io/jargonless-website/portfolio-web:latest
          docker push ghcr.io/jargonless-website/portfolio-web:${{ github.sha }}
          docker push ghcr.io/jargonless-website/portfolio-web:latest

      - name: Build & push API (latest + SHA)
        run: |
          docker build -t ghcr.io/jargonless-website/portfolio-api:${{ github.sha }} ./apps/api
          docker tag ghcr.io/jargonless-website/portfolio-api:${{ github.sha }} ghcr.io/jargonless-website/portfolio-api:latest
          docker push ghcr.io/jargonless-website/portfolio-api:${{ github.sha }}
          docker push ghcr.io/jargonless-website/portfolio-api:latest
