name: CD Staging

on:
  push:
    branches: [staging]

concurrency:
  group: cd-staging-${{ github.ref }}
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io
  IMAGE_WEB: ghcr.io/jargonless-website/portfolio-web
  IMAGE_API: ghcr.io/jargonless-website/portfolio-api
  STACK_NAME: portfolio-stg
  COMPOSE_PROJECT_NAME: portfolio-stg
  WORKSPACE_ROOT: /work/.deploy/staging
  HOST_PROJECT_ROOT: /work
  HOST_ENV_FILE: /work/infra/compose/.env.production.stg
  HOST_TUNNEL_FILE: /work/infra/compose/.env.tunnel.stg
  HOST_NGINX_CONFIG: /work/infra/nginx/nginx.staging.conf
  HOST_NGINX_SNIPPETS: /work/infra/nginx/snippets
  HOST_TUNNEL_VOLUME: /volume1/docker/portfolio/cloudflared-staging
  WEB_IMAGE_TAG: staging
  API_IMAGE_TAG: staging

jobs:
  deploy-staging:
    runs-on: self-hosted
    environment: staging

    steps:
      - name: Prepare staging workspace
        run: |
          set -euo pipefail
          mkdir -p "${WORKSPACE_ROOT}"
          if [ -d "${WORKSPACE_ROOT}/.git" ]; then
            echo "Repo exists → refresh staging branch"
            git -C "${WORKSPACE_ROOT}" fetch --all --prune
            git -C "${WORKSPACE_ROOT}" checkout staging || git -C "${WORKSPACE_ROOT}" checkout -b staging
            git -C "${WORKSPACE_ROOT}" reset --hard origin/staging
            git -C "${WORKSPACE_ROOT}" clean -fdx
          else
            echo "Fresh clone of staging branch into ${WORKSPACE_ROOT}"
            rm -rf "${WORKSPACE_ROOT:?}/"*
            git clone --branch staging https://github.com/jargonless-website/jargonless-portfolio "${WORKSPACE_ROOT}"
          fi

      - name: Copy staging configuration
        run: |
          set -euo pipefail
          [ -s "${HOST_ENV_FILE}" ] || { echo "::error::Missing ${HOST_ENV_FILE}"; exit 1; }
          [ -s "${HOST_TUNNEL_FILE}" ] || { echo "::error::Missing ${HOST_TUNNEL_FILE}"; exit 1; }
          [ -f "${HOST_NGINX_CONFIG}" ] || { echo "::error::Missing ${HOST_NGINX_CONFIG}"; exit 1; }
          mkdir -p "${WORKSPACE_ROOT}/infra/compose"
          cp "${HOST_ENV_FILE}" "${WORKSPACE_ROOT}/infra/compose/.env.production.stg"
          cp "${HOST_TUNNEL_FILE}" "${WORKSPACE_ROOT}/infra/compose/.env.tunnel.stg"
          mkdir -p "${WORKSPACE_ROOT}/infra/nginx"
          cp "${HOST_NGINX_CONFIG}" "${WORKSPACE_ROOT}/infra/nginx/nginx.staging.conf"
          if [ -d "${HOST_NGINX_SNIPPETS}" ]; then
            mkdir -p "${WORKSPACE_ROOT}/infra/nginx/snippets"
            rsync -a "${HOST_NGINX_SNIPPETS}/" "${WORKSPACE_ROOT}/infra/nginx/snippets/"
          else
            mkdir -p "${WORKSPACE_ROOT}/infra/nginx/snippets"
          fi
          mkdir -p "${HOST_TUNNEL_VOLUME}"

      - name: Inspect workspace
        run: |
          set -euo pipefail
          echo "Workspace compose dir"
          ls -al "${WORKSPACE_ROOT}/infra/compose" || true
          echo "Workspace nginx dir"
          ls -al "${WORKSPACE_ROOT}/infra/nginx" || true
          echo "Cloudflared staging host dir"
          ls -al "${HOST_TUNNEL_VOLUME}" || true

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push WEB (staging)
        working-directory: ${{ env.WORKSPACE_ROOT }}
        run: |
          set -euo pipefail
          docker build -t ${IMAGE_WEB}:${GITHUB_SHA} ./apps/web
          docker tag  ${IMAGE_WEB}:${GITHUB_SHA} ${IMAGE_WEB}:${WEB_IMAGE_TAG}
          docker push ${IMAGE_WEB}:${GITHUB_SHA}
          docker push ${IMAGE_WEB}:${WEB_IMAGE_TAG}

      - name: Build and push API (staging)
        working-directory: ${{ env.WORKSPACE_ROOT }}
        run: |
          set -euo pipefail
          docker build -t ${IMAGE_API}:${GITHUB_SHA} ./apps/api
          docker tag  ${IMAGE_API}:${GITHUB_SHA} ${IMAGE_API}:${API_IMAGE_TAG}
          docker push ${IMAGE_API}:${GITHUB_SHA}
          docker push ${IMAGE_API}:${API_IMAGE_TAG}

      - name: Deploy stack (staging)
        working-directory: ${{ env.WORKSPACE_ROOT }}
        env:
          COMPOSE_PROJECT_NAME: ${{ env.COMPOSE_PROJECT_NAME }}
          STACK_NAME: ${{ env.STACK_NAME }}
          APP_ENV_FILE: ${{ env.WORKSPACE_ROOT }}/infra/compose/.env.production.stg
          TUNNEL_ENV_FILE: ${{ env.WORKSPACE_ROOT }}/infra/compose/.env.tunnel.stg
          TUNNEL_VOLUME: ${{ env.HOST_TUNNEL_VOLUME }}
          WEB_IMAGE_TAG: ${{ env.WEB_IMAGE_TAG }}
          API_IMAGE_TAG: ${{ env.API_IMAGE_TAG }}
        run: |
          set -euo pipefail
          [ -s "${APP_ENV_FILE}" ] || { echo "::error::Missing ${APP_ENV_FILE}"; exit 1; }
          [ -s "${TUNNEL_ENV_FILE}" ] || { echo "::error::Missing ${TUNNEL_ENV_FILE}"; exit 1; }
          token_value="$(sed -n 's/^CLOUDFLARE_TUNNEL_TOKEN=//p' "${TUNNEL_ENV_FILE}")"
          [ -n "${token_value}" ] || { echo "::error::CLOUDFLARE_TUNNEL_TOKEN empty"; exit 1; }
          export CLOUDFLARE_TUNNEL_TOKEN="${token_value}"
          docker compose \
            -f infra/compose/docker-compose.yml \
            -f infra/compose/docker-compose.stg.yml \
            --env-file "${APP_ENV_FILE}" \
            up -d --remove-orphans nginx api jl_tunnel

      - name: Show container status
        run: |
          docker ps --format 'table {{.Names}}\t{{.Status}}\t{{.Image}}' | grep -E 'portfolio-stg-(nginx|api|jl_tunnel)' || true
