name: CI Core

on:
  push:
    branches: [ main, staging ]

jobs:
  compose-validate:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - name: Prepare dummy env files for Compose validation
        run: |
          mkdir -p infra/compose
          cat > infra/compose/.env.production <<'EOF'
          ENV=production
          CORS_ORIGINS=https://jargonless.ai
          EOF
          cat > infra/compose/.env.production.stg <<'EOF'
          ENV=staging
          CORS_ORIGINS=https://staging.jargonless.ai
          EOF

      - name: Validate Compose
        run: |
          docker compose -f infra/compose/docker-compose.yml config -q
          docker compose -f infra/compose/docker-compose.prod.yml config -q || true
          docker compose -f infra/compose/docker-compose.runner.yml config -q || true
