name: CD Prod

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: "Type EXACTLY: deploy-prod"
        required: true
        type: string

jobs:
  deploy-prod:
    if: inputs.confirm == 'deploy-prod' && github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v4

      - name: GHCR login
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u "${{ secrets.GHCR_USER }}" --password-stdin

      - name: SSH deploy to NAS (PROD)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.NAS_HOST }}
          username: ${{ secrets.NAS_USER }}
          key: ${{ secrets.NAS_SSH_KEY }}
          port: ${{ secrets.NAS_SSH_PORT }}
          script: |
            set -e
            cd /volume1/docker/portfolio
            git checkout main || true
            git fetch origin main
            git reset --hard origin/main

            echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u "${{ secrets.GHCR_USER }}" --password-stdin
            docker pull ghcr.io/jargonless-website/portfolio-web:latest
            docker pull ghcr.io/jargonless-website/portfolio-api:latest

            export COMPOSE_PROJECT_NAME=portfolio

            docker compose \
              -f infra/compose/docker-compose.yml \
              -f infra/compose/docker-compose.prod.yml \
              --env-file infra/compose/.env.production \
              up -d --remove-orphans nginx api

            docker ps --format 'table {{.Names}}\t{{.Status}}' | grep -E 'portfolio-(nginx|api)-1' || true
