name: CD Prod

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: "Type EXACTLY: deploy-prod"
        required: true
        type: string

jobs:
  deploy-prod:
    if: inputs.confirm == 'deploy-prod' && github.event_name != 'pull_request'
    runs-on: self-hosted
    environment: production
    env:
      WORKSPACE_ROOT: /work/.deploy/prod
      HOST_PROJECT_ROOT: /work
      APP_ENV_FILE: /work/infra/compose/.env.production
      TUNNEL_ENV_FILE: /work/infra/compose/.env.tunnel
      TUNNEL_VOLUME: /work/cloudflared
      NGINX_CONFIG_PATH: /work/infra/nginx/nginx.conf
      NGINX_SNIPPETS_PATH: /work/infra/nginx/snippets

    steps:
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Mark NAS repo mount as safe
        run: git config --global --add safe.directory /work

      - name: Prepare production workspace
        run: |
          set -euo pipefail
          mkdir -p "${WORKSPACE_ROOT}"
          if [ -d "${WORKSPACE_ROOT}/.git" ]; then
            echo "Repo exists → refresh main branch"
            git -C "${WORKSPACE_ROOT}" fetch --all --prune
            git -C "${WORKSPACE_ROOT}" checkout main || git -C "${WORKSPACE_ROOT}" checkout -b main
            git -C "${WORKSPACE_ROOT}" reset --hard origin/main
            git -C "${WORKSPACE_ROOT}" clean -fdx
          else
            echo "Fresh clone of main branch into ${WORKSPACE_ROOT}"
            rm -rf "${WORKSPACE_ROOT:?}/"*
            git clone --branch main https://github.com/jargonless-website/jargonless-portfolio "${WORKSPACE_ROOT}"
          fi

      - name: Inspect mounted NAS paths
        run: |
          set -euo pipefail
          echo "Contents of ${HOST_PROJECT_ROOT}/infra/compose"
          ls -al "${HOST_PROJECT_ROOT}/infra/compose" || true
          echo "Contents of ${HOST_PROJECT_ROOT}/infra/nginx"
          ls -al "${HOST_PROJECT_ROOT}/infra/nginx" || true
          echo "Contents of ${TUNNEL_VOLUME}"
          ls -al "${TUNNEL_VOLUME}" || true

      - name: Verify production env files on NAS
        run: |
          set -euo pipefail
          echo "::notice::Using production env file ${APP_ENV_FILE}"
          echo "::notice::Using production tunnel env file ${TUNNEL_ENV_FILE}"
          for file in "${APP_ENV_FILE}" "${TUNNEL_ENV_FILE}"; do
            if [ ! -f "$file" ]; then
              echo "::error file=$file::Expected production env file '$file' on NAS. Create it or supply secrets."
              exit 1
            fi
          done
          token_line="$(grep -E '^CLOUDFLARE_TUNNEL_TOKEN=' "${TUNNEL_ENV_FILE}" || true)"
          if [ -z "$token_line" ] || [ -z "${token_line#CLOUDFLARE_TUNNEL_TOKEN=}" ]; then
            echo "::error file=${TUNNEL_ENV_FILE}::CLOUDFLARE_TUNNEL_TOKEN missing or empty. Update the NAS file."
            exit 1
          fi

      - name: Verify production nginx config on NAS
        run: |
          set -euo pipefail
          if [ ! -f "${NGINX_CONFIG_PATH}" ]; then
            echo "::error file=${NGINX_CONFIG_PATH}::Missing production nginx configuration file on NAS."
            exit 1
          fi
          if [ ! -d "${NGINX_SNIPPETS_PATH}" ]; then
            echo "::warning ::Nginx snippets directory '${NGINX_SNIPPETS_PATH}' not found; creating empty directory."
            mkdir -p "${NGINX_SNIPPETS_PATH}"
          fi

      - name: Ensure Cloudflared volume directory exists
        run: |
          set -euo pipefail
          echo "::notice::Ensuring Cloudflared volume path ${TUNNEL_VOLUME} exists"
          mkdir -p "${TUNNEL_VOLUME}"

      - name: Pull images (latest)
        run: |
          docker pull ghcr.io/jargonless-website/portfolio-web:latest
          docker pull ghcr.io/jargonless-website/portfolio-api:latest

      - name: Deploy stack (prod)
        working-directory: ${{ env.WORKSPACE_ROOT }}
        env:
          COMPOSE_PROJECT_NAME: portfolio
          NGINX_CONFIG_PATH: ${{ env.NGINX_CONFIG_PATH }}
          NGINX_SNIPPETS_PATH: ${{ env.NGINX_SNIPPETS_PATH }}
          APP_ENV_FILE: ${{ env.APP_ENV_FILE }}
          TUNNEL_ENV_FILE: ${{ env.TUNNEL_ENV_FILE }}
          TUNNEL_VOLUME: ${{ env.TUNNEL_VOLUME }}
        run: |
          set -euo pipefail
          echo "Using paths for deployment:"
          echo "  NGINX_CONFIG_PATH: ${NGINX_CONFIG_PATH}"
          echo "  NGINX_SNIPPETS_PATH: ${NGINX_SNIPPETS_PATH}"
          echo "  TUNNEL_VOLUME: ${TUNNEL_VOLUME}"
          token_value="$(grep -E '^CLOUDFLARE_TUNNEL_TOKEN=' \"${TUNNEL_ENV_FILE}\" | head -n1 | cut -d'=' -f2-)"
          if [ -z "${token_value}" ]; then
            echo "::error::Unable to extract CLOUDFLARE_TUNNEL_TOKEN from ${TUNNEL_ENV_FILE}"
            exit 1
          fi
          export CLOUDFLARE_TUNNEL_TOKEN="${token_value}"
          trap 'unset CLOUDFLARE_TUNNEL_TOKEN' EXIT
          docker compose \
            -f infra/compose/docker-compose.yml \
            -f infra/compose/docker-compose.prod.yml \
            --env-file "${APP_ENV_FILE}" \
            up -d --remove-orphans nginx api jl_tunnel

      - name: Show container status
        run: docker ps --format 'table {{.Names}}\t{{.Status}}' | grep -E 'portfolio-(nginx|api|jl_tunnel)-1' || true
