name: CD Staging

on:
  push:
    branches: [ staging ]

jobs:
  deploy-staging:
    if: github.event_name != 'pull_request'
    runs-on: self-hosted

    steps:
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Update repo on NAS
        run: |
          set -e
          cd /volume1/docker/portfolio
          if ! git rev-parse --git-dir >/dev/null 2>&1; then
            git clone https://github.com/jargonless-website/jargonless-portfolio .
          fi
          git fetch origin staging
          git reset --hard origin/staging

      - name: Pull images (latest)
        run: |
          docker pull ghcr.io/jargonless-website/portfolio-web:latest
          docker pull ghcr.io/jargonless-website/portfolio-api:latest

      - name: Deploy stack (staging)
        env:
          COMPOSE_PROJECT_NAME: portfolio-stg
        run: |
          cd /volume1/docker/portfolio
          docker compose \
            -f infra/compose/docker-compose.yml \
            -f infra/compose/docker-compose.prod.yml \
            --env-file infra/compose/.env.production.stg \
            up -d --remove-orphans nginx api

      - name: Show container status
        run: docker ps --format 'table {{.Names}}\t{{.Status}}' | grep -E 'portfolio-stg_(nginx|api)_1|cloudflared-staging' || true
