name: CD Staging

on:
  push:
    branches: [ staging ]

jobs:
  deploy-staging:
    if: github.event_name != 'pull_request'
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4


      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_TOKEN }}


      - name: Build & push images (staging uses :latest)
        run: |
          docker build -t ghcr.io/jargonless-website/portfolio-web:${{ github.sha }} ./apps/web
          docker tag ghcr.io/jargonless-website/portfolio-web:${{ github.sha }} ghcr.io/jargonless-website/portfolio-web:latest
          docker push ghcr.io/jargonless-website/portfolio-web:${{ github.sha }}
          docker push ghcr.io/jargonless-website/portfolio-web:latest
          docker build -t ghcr.io/jargonless-website/portfolio-api:${{ github.sha }} ./apps/api
          docker tag ghcr.io/jargonless-website/portfolio-api:${{ github.sha }} ghcr.io/jargonless-website/portfolio-api:latest
          docker push ghcr.io/jargonless-website/portfolio-api:${{ github.sha }}
          docker push ghcr.io/jargonless-website/portfolio-api:latest

      - name: SSH deploy to NAS (STAGING)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.NAS_HOST }}
          username: ${{ secrets.NAS_USER }}
          key: ${{ secrets.NAS_SSH_KEY }}
          port: ${{ secrets.NAS_SSH_PORT }}
          script: |
            set -e
            cd /volume1/docker/portfolio

            # ensure staging branch exists and is current
            if ! git show-ref --verify --quiet refs/heads/staging; then
              git fetch origin staging:staging
            else
              git fetch origin staging
            fi
            git checkout staging
            git reset --hard origin/staging

            echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u "${{ secrets.GHCR_USER }}" --password-stdin
            docker pull ghcr.io/jargonless-website/portfolio-web:latest
            docker pull ghcr.io/jargonless-website/portfolio-api:latest

            export COMPOSE_PROJECT_NAME=portfolio-stg

            docker compose \
              -f infra/compose/docker-compose.yml \
              -f infra/compose/docker-compose.prod.yml \
              --env-file infra/compose/.env.production.stg \
              up -d --remove-orphans nginx api
