name: Week 0 CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  compose-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Docker setup
        uses: docker/setup-buildx-action@v3
      - name: Validate Compose
        run: docker compose -f infra/compose/docker-compose.yml config -q

  api-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build API image
        run: docker build -t jargonless/api:week0 ./apps/api
